<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="RetrieveVoiceProfileProcessorImpl" targetNamespace="http://CILSBVoiceServicesMod/RetrieveVoiceProfileProcessorImplArtifacts" xmlns:plnk="http://schemas.xmlsoap.org/ws/2004/03/partner-link/" xmlns:tns="http://CILSBVoiceServicesMod/RetrieveVoiceProfileProcessorImplArtifacts" xmlns:wsdl0="http://CILSBVoiceServicesLib/VoiceProcessorIF" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <plnk:partnerLinkType name="VoiceProcessorIFPLT">
    <plnk:role name="Interface">
      <plnk:portType name="wsdl0:VoiceProcessorIF"/>
    </plnk:role>
  </plnk:partnerLinkType>
    <wsdl:import location="VoiceProcessorIF.wsdl" namespace="http://CILSBVoiceServicesLib/VoiceProcessorIF"/>
</wsdl:definitions>