<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="VoiceServicesIF" targetNamespace="http://CILSBVoiceServicesLib/VoiceServicesIF" xmlns:tns="http://CILSBVoiceServicesLib/VoiceServicesIF" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <wsdl:types>
    <xsd:schema targetNamespace="http://CILSBVoiceServicesLib/VoiceServicesIF">
            <xsd:import schemaLocation="custProfileQueryRequest.xsd"/>
            <xsd:import schemaLocation="custProfileQueryResponse.xsd"/>
            <xsd:element name="retrieveVoiceProfile">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element ref="customerProfileQueryRequest"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="retrieveVoiceProfileResponse">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element ref="custProfileQueryResponse"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:schema>
  </wsdl:types>
    <wsdl:message name="retrieveVoiceProfileRequestMsg">
    <wsdl:part element="tns:retrieveVoiceProfile" name="retrieveVoiceProfileParameters"/>
  </wsdl:message>
    <wsdl:message name="retrieveVoiceProfileResponseMsg">
    <wsdl:part element="tns:retrieveVoiceProfileResponse" name="retrieveVoiceProfileResult"/>
  </wsdl:message>
    <wsdl:portType name="RetrieveVoiceProfileService">
    <wsdl:operation name="retrieveVoiceProfile">
      <wsdl:input message="tns:retrieveVoiceProfileRequestMsg" name="retrieveVoiceProfileRequest"/>
      <wsdl:output message="tns:retrieveVoiceProfileResponseMsg" name="retrieveVoiceProfileResponse"/>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>